public class Account(){

    public String accountType;
    public String authorizedUser1;
    public String authorizedUser2;
    public Decimal balance;
    public Integer accountNumber;

    Account account = new Account();

    public Decimal accountBalance(Decimal amount{
        balance += amount;

    }

    public String authorizedUser(){
        //TODO: verify age and customer name(s)
    }


}
